Repository Baby-on-top/Lignin-Be, pull requests merged in 2023-07, with the labels that each got.

#8 3-be-exception-handler
  src/main/java/baby/lignin/config/OpenApiConfig.java
  src/main/java/baby/lignin/exception/ErrorCode.java
  src/main/java/baby/lignin/exception/ErrorControllerAdvice.java
  src/main/java/baby/lignin/exception/ErrorResponse.java
  src/main/java/baby/lignin/template/suppoert/empty.txt
  src/main/java/baby/lignin/template/support/empty.txt
  src/main/resources/application.properties
Labels: back, feature

#9 be-response-support
  src/main/java/baby/lignin/support/ApiResponse.java
  src/main/java/baby/lignin/support/ApiResponseGenerator.java
  src/main/java/baby/lignin/support/MessageCode.java
Labels: back

#12 Feat : Logout,Unlink api 추가
  src/main/java/baby/lignin/auth/controller/MemberController.java
  src/main/java/baby/lignin/auth/service/MemberService.java
  src/main/java/baby/lignin/auth/service/MemberServiceImpl.java
Labels: back, feature

#10 Board#6
  src/main/java/baby/lignin/board/controller/BoardRestController.java
  src/main/java/baby/lignin/board/entity/BoardEntity.java
  src/main/java/baby/lignin/board/model/request/BoardAddRequest.java
  src/main/java/baby/lignin/board/model/request/BoardBrowseRequest.java
  src/main/java/baby/lignin/board/model/request/BoardDeleteRequest.java
  src/main/java/baby/lignin/board/model/request/BoardEditRequest.java
  src/main/java/baby/lignin/board/model/response/BoardResponse.java
  src/main/java/baby/lignin/board/repository/BoardRepository.java
  src/main/java/baby/lignin/board/service/BoardService.java
  src/main/java/baby/lignin/board/support/ApiResponse.java
  src/main/java/baby/lignin/board/support/ApiResponseGenerator.java
  src/main/java/baby/lignin/board/support/MessageCode.java
  src/main/java/baby/lignin/board/support/converter/BoardConverter.java
Labels: back, feature

#20 Auth #1
  src/main/java/baby/lignin/auth/config/WebConfig.java
  src/main/java/baby/lignin/auth/controller/MemberController.java
  src/main/java/baby/lignin/auth/service/MemberServiceImpl.java
Labels: back, feature

#23 be-image-refactor
  src/main/java/baby/lignin/image/controller/AwsS3Controller.java
  src/main/java/baby/lignin/image/service/AwsS3Service.java
Labels: back, refactoring

#24 Fix : CORS 설정 추가 #1
  src/main/java/baby/lignin/auth/config/WebConfig.java
Labels: bug, back, feature

#25 Fix : login API Header - Authorization -> Token 변경 #1
  src/main/java/baby/lignin/auth/config/TokenResolver.java
  src/main/java/baby/lignin/auth/controller/MemberController.java
Labels: bug, back

#27 Chore : auth -> ApiResponse, Generator 삭제 , main-support로 경로 수정
  src/main/java/baby/lignin/auth/controller/MemberController.java
  src/main/java/baby/lignin/auth/util/ApiResponse.java
  src/main/java/baby/lignin/auth/util/ApiResponseGenerator.java
  src/main/java/baby/lignin/auth/util/MessageCode.java
  src/main/java/baby/lignin/support/MessageCode.java
Labels: back

#34 Feat : git-action slack 부분 수정 #7
  .github/workflows/ci-cd-prod.yml
Labels: back

#38 Workspace#18
  src/main/java/baby/lignin/workspace/controller/WorkSpaceController.java
  src/main/java/baby/lignin/workspace/entity/WorkSpaceEntitiy.java
  src/main/java/baby/lignin/workspace/entity/WorkSpaceMemberEntity.java
  src/main/java/baby/lignin/workspace/model/request/WorkSpaceCreateRequest.java
  src/main/java/baby/lignin/workspace/model/request/WorkSpaceDeleteRequest.java
  src/main/java/baby/lignin/workspace/model/request/WorkSpaceRequest.java
  src/main/java/baby/lignin/workspace/model/request/WorkSpaceUpdateRequest.java
  src/main/java/baby/lignin/workspace/model/response/WorkSpaceMemberResponse.java
  src/main/java/baby/lignin/workspace/model/response/WorkSpaceResponse.java
  src/main/java/baby/lignin/workspace/repository/WorkspaceMemberRepository.java
  src/main/java/baby/lignin/workspace/repository/WorkspaceRepository.java
  src/main/java/baby/lignin/workspace/service/WorkspaceService.java
  src/main/java/baby/lignin/workspace/service/WorkspaceServiceImpl.java
  src/main/java/baby/lignin/workspace/support/converter/WorkspaceConverter.java
  src/main/java/baby/lignin/workspace/support/converter/WorkspaceCreateConverter.java
Labels: back, feature

#39 Chore : createId - Swagger(JsonIgnore) 추가
  src/main/java/baby/lignin/workspace/model/request/WorkSpaceCreateRequest.java
Labels: back, feature

#42 Chore : webConfig 위치 수정
  src/main/java/baby/lignin/config/WebConfig.java
Labels: bug, back

#45 Fix : 카카오 프로필 이미지 못가져오는 이슈 수정 #1
  src/main/java/baby/lignin/auth/model/auth/KakaoProfile.java
  src/main/java/baby/lignin/auth/service/MemberServiceImpl.java
Labels: bug, back

#46 Develop
  src/main/java/baby/lignin/auth/model/auth/KakaoProfile.java
  src/main/java/baby/lignin/auth/service/MemberServiceImpl.java
Labels: bug, back

#48 Blue green#47
  .github/workflows/ci-cd-dev.yml
  .github/workflows/ci-cd-prod.yml
  .platform/nginx/nginx.blue.conf
  .platform/nginx/nginx.green.conf
  deploy.sh
  docker-compose.yml
Labels: back

#51 Redis#19
  build.gradle
  docker-compose.yml
  src/main/java/baby/lignin/LigninApplication.java
  src/main/java/baby/lignin/board/service/BoardService.java
  src/main/java/baby/lignin/config/RedisCacheConfig.java
  src/main/java/baby/lignin/config/RedisConfig.java
Labels: back, feature

#53 Board#6
  src/main/java/baby/lignin/board/controller/BoardMemberRestController.java
  src/main/java/baby/lignin/board/controller/BoardRestController.java
  src/main/java/baby/lignin/board/entity/BoardMemberEntity.java
  src/main/java/baby/lignin/board/model/request/BoardMemberDeleteRequest.java
  src/main/java/baby/lignin/board/model/request/BoardMemberInviteRequest.java
  src/main/java/baby/lignin/board/model/response/BoardMemberResponse.java
  src/main/java/baby/lignin/board/repository/BoardMemberRepository.java
  src/main/java/baby/lignin/board/repository/BoardRepository.java
  src/main/java/baby/lignin/board/service/BoardMemberService.java
  src/main/java/baby/lignin/board/service/BoardService.java
  src/main/java/baby/lignin/board/support/converter/BoardMemberConverter.java
Labels: back, feature

#54 Hotfix : board-invite merge 과정 충돌 해결 #36
  src/main/java/baby/lignin/board/service/BoardService.java
Labels: back, feature

#55 Chore : webConfig 수정 #18
  src/main/java/baby/lignin/config/WebConfig.java
Labels: bug, back

#56 Develop
  .github/workflows/ci-cd-dev.yml
  .github/workflows/ci-cd-prod.yml
  .platform/nginx/nginx.blue.conf
  .platform/nginx/nginx.green.conf
  build.gradle
  deploy.sh
  docker-compose.yml
  src/main/java/baby/lignin/LigninApplication.java
  src/main/java/baby/lignin/board/controller/BoardMemberRestController.java
  src/main/java/baby/lignin/board/controller/BoardRestController.java
  src/main/java/baby/lignin/board/entity/BoardMemberEntity.java
  src/main/java/baby/lignin/board/model/request/BoardMemberDeleteRequest.java
  src/main/java/baby/lignin/board/model/request/BoardMemberInviteRequest.java
  src/main/java/baby/lignin/board/model/response/BoardMemberResponse.java
  src/main/java/baby/lignin/board/repository/BoardMemberRepository.java
  src/main/java/baby/lignin/board/repository/BoardRepository.java
  src/main/java/baby/lignin/board/service/BoardMemberService.java
  src/main/java/baby/lignin/board/service/BoardService.java
  src/main/java/baby/lignin/board/support/converter/BoardMemberConverter.java
  src/main/java/baby/lignin/config/RedisCacheConfig.java
  src/main/java/baby/lignin/config/RedisConfig.java
  src/main/java/baby/lignin/config/WebConfig.java
Labels: bug, back

#57 Fix : CORS - config 수정 #1
  src/main/java/baby/lignin/auth/controller/MemberController.java
  src/main/java/baby/lignin/config/WebConfig.java
  src/main/java/baby/lignin/workspace/controller/WorkSpaceController.java
Labels: back, feature

#63 Workspace#18
  src/main/java/baby/lignin/auth/controller/MemberController.java
  src/main/java/baby/lignin/auth/service/MemberService.java
  src/main/java/baby/lignin/auth/service/MemberServiceImpl.java
  src/main/java/baby/lignin/config/WebConfig.java
  src/main/java/baby/lignin/workspace/controller/WorkSpaceController.java
  src/main/java/baby/lignin/workspace/repository/WorkspaceMemberRepository.java
  src/main/java/baby/lignin/workspace/service/WorkspaceService.java
  src/main/java/baby/lignin/workspace/service/WorkspaceServiceImpl.java
  src/main/java/baby/lignin/workspace/support/converter/WorkspaceCreateConverter.java
Labels: back, feature
